### PR TITLE
stop overwriting "esc" behavior; stop overwriting input.conf behavior

### PR DESCRIPTION
**Pull request by Brett824**
Just started using plex-mpv-shim and noticed that my custom keybinds weren't working. In the process I also discovered that the default behavior/keybind for "ESC" was overridden as well. This PR does two things:

1. Restore the default escape key behavior (`set fullscreen no`) if the OSD menu isn't open.
2. **PARTIALLY** implements a system that reads keybinds from the input.conf and uses those instead of the defaults for keybinds that are overridden by plex-mpv-shim (ESC, UP, DOWN, LEFT, RIGHT, SPACE, etc). I only implemented this for "ESC" because I wanted your thoughts on this approach/idea before moving forward. If this isn't something you want to include, I can edit this PR to only include the escape fix.

(p.s. sorry for minor whitespace edits in the diff, I can't get my editor to not do that)

### CODE REVIEW

**Comment by iwalton3** [comment]
Someone logged a similar issue with Jellyfin MPV Shim (https://github.com/iwalton3/jellyfin-mpv-shim/issues/62#issuecomment-625790756).

There is definitely something that should be done to handle custom keyboard shortcuts and make current ones configurable, as that is a pain point for users and I want to accommodate customization as much as possible. I'm going to investigate what I can do via the MPV API before resorting to parsing the mpv config files myself though, since the MPV config should ideally be processed only by MPV.

**Comment by Brett824** [comment]
I looked at the MPV API briefly and didn't find an obviously good solution to this problem other than what I implemented. I understand the hesitation though.

Would you be amenable to a second PR that just fixes the escape key problem? That seems like a less ambiguous bug.

**Comment by iwalton3** [comment]
Yes adding ESC for exiting fullscreen is perfectly fine, I can approve that and merge it to both projects.

**Comment by Brett824** [comment]
I've created #16 that includes just that fix. You can close this or use what I've done if you decide on how you want to implement the feature.

**Comment by iwalton3** [comment]
So I looked into this more. There is the `input_bindings` property, which allows reading the command. The problem is these are raw MPV commands encoded as strings.

I've decided what I'll do is keep the ESC change (since that one is kind of odd) and also make custom command able to be rebound and disabled via the config. While this isn't perfect, it should cover most customization.

**Comment by iwalton3** [comment]
I have created a change that allows changing the keybinds. It is planned for the next release.

**Pull request merged**
